name: Build

on:
  push:
    branches:    
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python #安装python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
    - name: Install
      run: |
        pip install pyocd nrfutil intelhex
    
    - name: cmake
      run: |  
        wget https://cmake.org/files/v3.24/cmake-3.24.2-linux-x86_64.tar.gz
        tar zxvf cmake-3.24.2-linux-x86_64.tar.gz
        sudo mv cmake-3.24.2-linux-x86_64 /opt/cmake-3.24.2
        sudo ln -sf /opt/cmake-3.24.2/bin/*  /usr/bin/
    
    - name: arm-none-eabi
      run: |  
        wget https://developer.arm.com/-/media/Files/downloads/gnu/11.2-2022.02/binrel/gcc-arm-11.2-2022.02-x86_64-arm-none-eabi.tar.xz 
        tar -xvf gcc-arm-11.2-2022.02-x86_64-arm-none-eabi.tar.xz
        sudo mv gcc-arm-11.2-2022.02-x86_64-arm-none-eabi /opt/arm-none-eabi
        sudo ln -sf /opt/arm-none-eabi/bin/*  /usr/bin/
    
    - name: nRF5_SDK
      run: | 
        wget https://www.nordicsemi.com/-/media/Software-and-other-downloads/SDKs/nRF5/Binaries/nRF5_SDK_17.1.0_ddde560.zip
        unzip nRF5_SDK_17.1.0_ddde560.zip
        git clone https://github.com/canokeys/canokey-nrf52.git
        cp -r /home/runner/work/nrf52/nrf52/nRF5_SDK_17.1.0_ddde560 /home/runner/work/nrf52/nrf52/canokey-nrf52/nrf_sdk
        
    - name: build
      run: | 
        cd home/runner/work/nrf52/nrf52/canokey-nrf52
        git submodule update --init --recursive
        mkdir build
        cd build
        cmake -DCROSS_COMPILE=/opt/arm-none-eabi/bin/arm-none-eabi- \
        -DCMAKE_TOOLCHAIN_FILE=../toolchain.cmake \
        -DCMAKE_BUILD_TYPE=Release ..
        
    - name: u2f
      run: | 
        cd /canokey-nrf52/build
        make canokey_flash.uf2
